### ISSUE TITLE
Crash while adjusting the volume

### ISSUE THREAD

**Issue by LanceJZ** [strawberrymusicplayer/strawberry#1089]
- [x] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [x] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [x] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
While adjusting the volume using the slider, causes program to crash.

**To Reproduce**
Adjust volume while mp3 is playing.

**Expected behavior**
Volume to change.

**Screenshots:**
NA

**System Information:**
 - Operating system:Windows 10 21H2
 - Strawberry Version:1.0.11

**Additional context**
This just started with the current version after the update.

**Comment by jonaski** [comment]
It works here without a crash. Are you using the MinGW or MSVC release?

**Comment by mataha** [comment]
I've encountered the same issue, though I can't reproduce it deterministically - it crashes about 50% of the time.

**Comment by SamuelBucher** [comment]
Same issue. This bug is repeatable and highly inconvenient. I can't figure out when exactly the scroll wheel causes a crash (going between 68% and 72% is fine, for example, but above 72% consistently crashes the app), but it happens often enough (roughly every 2nd-3rd time) to make the app virtually unusable. This applies to the Windows version 1.0.11, both MSVC and MinGW.

**Comment by jonaski** [comment]
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ff8662fb27b in ntdll!RtlAllocateHeap () from C:\Windows\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x00007ff8662fb27b in ntdll!RtlAllocateHeap () from C:\Windows\SYSTEM32\ntdll.dll
#1  0x00007ff863f7fde6 in ucrtbase!_malloc_base () from C:\Windows\System32\ucrtbase.dll
#2  0x00007fffd1a3a069 in allocateData (allocSize=<optimized out>) at ../qtbase-everywhere-src-6.4.1/src/corelib/tools/qarraydata.cpp:142
#3  0x00007fffd1a3a3c1 in QArrayData::allocate (dptr=dptr@entry=0x8f2fc04188, objectSize=objectSize@entry=16, alignment=alignment@entry=8, capacity=<optimized out>, option=QArrayData::Grow)
    at ../qtbase-everywhere-src-6.4.1/src/corelib/tools/qarraydata.cpp:191
#4  0x00007fffb7990fa6 in QTypedArrayData<std::pair<unsigned int, QMetaObject const*> >::allocate (capacity=<optimized out>, option=<optimized out>)
    at include/QtCore/../../../qtbase-everywhere-src-6.4.1/src/corelib/tools/qarraydata.h:105
#5  0x00007fffb79e5d60 in QArrayDataPointer<std::pair<unsigned int, QMetaObject const*> >::allocateGrow (from=..., n=n@entry=1, position=position@entry=QArrayData::GrowsAtEnd)
    at include/QtCore/../../../qtbase-everywhere-src-6.4.1/src/corelib/tools/qarraydatapointer.h:352
#6  0x00007fffb79e5fd7 in QArrayDataPointer<std::pair<unsigned int, QMetaObject const*> >::reallocateAndGrow (this=0x8f2fc043d0, where=QArrayData::GrowsAtEnd, n=1, old=0x0)
    at include/QtCore/../../../qtbase-everywhere-src-6.4.1/src/corelib/tools/qarraydatapointer.h:213
#7  0x00007fffb79e5f80 in QArrayDataPointer<std::pair<unsigned int, QMetaObject const*> >::detachAndGrow (this=this@entry=0x8f2fc043d0, where=where@entry=QArrayData::GrowsAtEnd, n=n@entry=1, data=data@entry=0x0, old=old@entry=0x0)
    at include/QtCore/../../../qtbase-everywhere-src-6.4.1/src/corelib/tools/qarraydatapointer.h:194
#8  0x00007fffb7a42ed9 in QtPrivate::QPodArrayOps<std::pair<unsigned int, QMetaObject const*> >::emplace<std::pair<unsigned int, QMetaObject const*> const&> (this=this@entry=0x8f2fc043d0, i=0)
    at include/QtCore/../../../qtbase-everywhere-src-6.4.1/src/corelib/tools/qarraydataops.h:174
#9  0x00007fffb7a1e954 in QList<std::pair<unsigned int, QMetaObject const*> >::emplaceBack<std::pair<unsigned int, QMetaObject const*> const&> (this=this@entry=0x8f2fc043d0)
    at include/QtCore/../../../qtbase-everywhere-src-6.4.1/src/corelib/tools/qlist.h:852
#10 0x00007fffb7a8076e in QList<std::pair<unsigned int, QMetaObject const*> >::append (t=..., this=0x8f2fc043d0) at include/QtCore/../../../qtbase-everywhere-src-6.4.1/src/corelib/tools/qlist.h:433
#11 QMultiHash<QObject*, std::pair<unsigned int, QMetaObject const*> >::values (this=this@entry=0x2099b12fa20, key=@0x8f2fc04418: 0x2099f07b720) at include/QtCore/../../../qtbase-everywhere-src-6.4.1/src/corelib/tools/qhash.h:1677
#12 0x00007fffb789ba07 in QAccessibleCache::idForObject (this=0x2099b12fa00, obj=<optimized out>, obj@entry=0x2099f07b720) at ../qtbase-everywhere-src-6.4.1/src/gui/accessible/qaccessiblecache.cpp:79
#13 0x00007fffb789a5a0 in QAccessible::queryAccessibleInterface (object=0x2099f07b720) at ../qtbase-everywhere-src-6.4.1/src/gui/accessible/qaccessible.cpp:644
#14 0x00007fffb789b027 in QAccessibleEvent::accessibleInterface (this=0x8f2fc045c0) at ../qtbase-everywhere-src-6.4.1/src/gui/accessible/qaccessible.cpp:1732
#15 0x00007fffb7898c95 in QAccessible::updateAccessibility (event=event@entry=0x8f2fc045c0) at ../qtbase-everywhere-src-6.4.1/src/gui/accessible/qaccessible.cpp:847
#16 0x00007fffaaf0481a in QAbstractSlider::setValue (this=0x2099f07b720, value=59) at ../qtbase-everywhere-src-6.4.1/src/widgets/widgets/qabstractslider.cpp:509
#17 0x00007ff6dde0b1d8 in SliderSlider::setValue (this=0x2099f07b720, value=59) at /persistent-data/mingw/windows-debug-x64/source/src/widgets/volumeslider.cpp:155
#18 0x00007ff6dde0b182 in SliderSlider::SetValue (this=0x2099f07b720, value=59) at /persistent-data/mingw/windows-debug-x64/source/src/widgets/volumeslider.cpp:146
#19 0x00007ff6de1c163f in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<unsigned int>, void, void (SliderSlider::*)(unsigned int)>::call (f=&virtual table offset 432, o=0x2099f07b720, arg=0x8f2fc04910)
    at /persistent-data/mingw/mxe-debug/source/usr/x86_64-w64-mingw32.shared/qt6/include/QtCore/qobjectdefs_impl.h:135
#20 0x00007ff6de2036ec in QtPrivate::FunctionPointer<void (SliderSlider::*)(unsigned int)>::call<QtPrivate::List<unsigned int>, void> (f=&virtual table offset 432, o=0x2099f07b720, arg=0x8f2fc04910)
    at /persistent-data/mingw/mxe-debug/source/usr/x86_64-w64-mingw32.shared/qt6/include/QtCore/qobjectdefs_impl.h:172
#21 0x00007ff6de1cc89a in QtPrivate::QSlotObject<void (SliderSlider::*)(unsigned int), QtPrivate::List<unsigned int>, void>::impl (which=1, this_=0x2099fbcf0e0, r=0x2099f07b720, a=0x8f2fc04910, ret=0x0)
    at /persistent-data/mingw/mxe-debug/source/usr/x86_64-w64-mingw32.shared/qt6/include/QtCore/qobjectdefs_impl.h:383
#22 0x00007fffd1b0e7e9 in QtPrivate::QSlotObjectBase::call (a=0x8f2fc04910, r=0x2099f07b720, this=0x2099fbcf0e0) at include/QtCore/../../../qtbase-everywhere-src-6.4.1/src/corelib/kernel/qobjectdefs_impl.h:363
#23 doActivate<false> (sender=0x2099ac283f0, signal_index=11, argv=0x8f2fc04910) at ../qtbase-everywhere-src-6.4.1/src/corelib/kernel/qobject.cpp:3972
#24 0x00007fffd19c8c48 in QMetaObject::activate (sender=0x2099ac283f0, m=<optimized out>, local_signal_index=8, argv=0x8f2fc04910) at ../qtbase-everywhere-src-6.4.1/src/corelib/kernel/qobject.cpp:4032
#25 0x00007ff6ddef4867 in PlayerInterface::VolumeChanged (this=0x2099ac283f0, _t1=59) at /persistent-data/mingw/windows-debug-x64/source/build/src/core/moc_player.cpp:714
#26 0x00007ff6ddc7c946 in Player::SetVolumeFromEngine (this=0x2099ac283f0, volume=59) at /persistent-data/mingw/windows-debug-x64/source/src/core/player.cpp:664
#27 0x00007ff6de1c16df in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<unsigned int>, void, void (Player::*)(unsigned int)>::call (f=&virtual table offset 232, o=0x2099ac283f0, arg=0x8f2fc04be0)
    at /persistent-data/mingw/mxe-debug/source/usr/x86_64-w64-mingw32.shared/qt6/include/QtCore/qobjectdefs_impl.h:135
#28 0x00007ff6de20a70c in QtPrivate::FunctionPointer<void (Player::*)(unsigned int)>::call<QtPrivate::List<unsigned int>, void> (f=&virtual table offset 232, o=0x2099ac283f0, arg=0x8f2fc04be0)
    at /persistent-data/mingw/mxe-debug/source/usr/x86_64-w64-mingw32.shared/qt6/include/QtCore/qobjectdefs_impl.h:172
#29 0x00007ff6de1e510a in QtPrivate::QSlotObject<void (Player::*)(unsigned int), QtPrivate::List<unsigned int>, void>::impl (which=1, this_=0x2099f7ccc80, r=0x2099ac283f0, a=0x8f2fc04be0, ret=0x0)
    at /persistent-data/mingw/mxe-debug/source/usr/x86_64-w64-mingw32.shared/qt6/include/QtCore/qobjectdefs_impl.h:383
#30 0x00007fffd1b0e7e9 in QtPrivate::QSlotObjectBase::call (a=0x8f2fc04be0, r=0x2099ac283f0, this=0x2099f7ccc80) at include/QtCore/../../../qtbase-everywhere-src-6.4.1/src/corelib/kernel/qobjectdefs_impl.h:363
#31 doActivate<false> (sender=0x2099ac8c070, signal_index=13, argv=0x8f2fc04be0) at ../qtbase-everywhere-src-6.4.1/src/corelib/kernel/qobject.cpp:3972
#32 0x00007fffd19c8c48 in QMetaObject::activate (sender=0x2099ac8c070, m=<optimized out>, local_signal_index=10, argv=0x8f2fc04be0) at ../qtbase-everywhere-src-6.4.1/src/corelib/kernel/qobject.cpp:4032
#33 0x00007ff6ddef8775 in Engine::Base::VolumeChanged (this=0x2099ac8c070, _t1=59) at /persistent-data/mingw/windows-debug-x64/source/build/src/engine/moc_enginebase.cpp:452
#34 0x00007ff6ddcb162e in Engine::Base::UpdateVolume (this=0x2099ac8c070, volume=59) at /persistent-data/mingw/windows-debug-x64/source/src/engine/enginebase.cpp:105
#35 0x00007ff6de1c181f in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<unsigned int>, void, void (Engine::Base::*)(unsigned int)>::call (
    f=(void (Engine::Base::*)(Engine::Base * const, unsigned int)) 0x7ff6ddcb1606 <Engine::Base::UpdateVolume(unsigned int)>, o=0x2099ac8c070, arg=0x8f2fc04ea0)
    at /persistent-data/mingw/mxe-debug/source/usr/x86_64-w64-mingw32.shared/qt6/include/QtCore/qobjectdefs_impl.h:135
#36 0x00007ff6de20bf0c in QtPrivate::FunctionPointer<void (Engine::Base::*)(unsigned int)>::call<QtPrivate::List<unsigned int>, void> (
    f=(void (Engine::Base::*)(Engine::Base * const, unsigned int)) 0x7ff6ddcb1606 <Engine::Base::UpdateVolume(unsigned int)>, o=0x2099ac8c070, arg=0x8f2fc04ea0)
    at /persistent-data/mingw/mxe-debug/source/usr/x86_64-w64-mingw32.shared/qt6/include/QtCore/qobjectdefs_impl.h:172
#37 0x00007ff6de1ea50a in QtPrivate::QSlotObject<void (Engine::Base::*)(unsigned int), QtPrivate::List<unsigned int>, void>::impl (which=1, this_=0x2099df689e0, r=0x2099ac8c070, a=0x8f2fc04ea0, ret=0x0)
    at /persistent-data/mingw/mxe-debug/source/usr/x86_64-w64-mingw32.shared/qt6/include/QtCore/qobjectdefs_impl.h:383
#38 0x00007fffd1b0e7e9 in QtPrivate::QSlotObjectBase::call (a=0x8f2fc04ea0, r=0x2099ac8c070, this=0x2099df689e0) at include/QtCore/../../../qtbase-everywhere-src-6.4.1/src/corelib/kernel/qobjectdefs_impl.h:363
#39 doActivate<false> (sender=0x2099af0ca80, signal_index=6, argv=0x8f2fc04ea0) at ../qtbase-everywhere-src-6.4.1/src/corelib/kernel/qobject.cpp:3972
#40 0x00007fffd19c8c48 in QMetaObject::activate (sender=0x2099af0ca80, m=<optimized out>, local_signal_index=3, argv=0x8f2fc04ea0) at ../qtbase-everywhere-src-6.4.1/src/corelib/kernel/qobject.cpp:4032
#41 0x00007ff6ddf2bccf in GstEnginePipeline::VolumeChanged (this=0x2099af0ca80, _t1=59) at /persistent-data/mingw/windows-debug-x64/source/build/src/engine/moc_gstenginepipeline.cpp:346
#42 0x00007ff6dde6c88f in GstEnginePipeline::VolumeCallback (self=0x2099af0ca80) at /persistent-data/mingw/windows-debug-x64/source/src/engine/gstenginepipeline.cpp:846
```

**Comment by jonaski** [comment]
if it's only the mouse wheel, not with click and drag, it should hopefully be fixed, can you test this one: https://builds.strawberrymusicplayer.org/windows/StrawberrySetup-1.0.11.7.g04f010aa-msvc-x64.exe

**Comment by El-Tacos** [comment]
I Hello,
I have the same bug with version 1.0.12-msvc-x64 but only with the volume adjustment with keyboard shortcuts. 

With the slider or the mouse wheel it works.

**Comment by jonaski** [comment]
@SamuelBucher @El-Tacos 
I did another fix 2 days ago after version 1.0.2, can you try with the latest from https://builds.strawberrymusicplayer.org/windows/ and report back.
Currently https://builds.strawberrymusicplayer.org/windows/StrawberrySetup-1.0.12.10.gdb55f314-msvc-x64.exe or https://builds.strawberrymusicplayer.org/windows/StrawberrySetup-1.0.12.10.gdb55f314-mingw-x64.exe

**Comment by SamuelBucher** [comment]
Sorry for the wait. Yes, it seems to work now. Thank you.

**Comment by El-Tacos** [comment]
Hello,
It works fine with version 1.0.12.10.gdb55f314-msvc-x64.
Thank you!
