### ISSUE TITLE
Crash related to album shuffle

### ISSUE THREAD

**Issue by elijahknaperek** [strawberrymusicplayer/strawberry#1588]
- [X] I have checked the [FAQ](https://wiki.strawberrymusicplayer.org/wiki/FAQ) for answers.
- [X] I have checked the [Changelog](https://github.com/strawberrymusicplayer/strawberry/blob/master/Changelog) that the issue is not already fixed. 
- [X] I believe this issue is a bug, and not a general technical issue, question or feature requests that can be discussed on the [forum](https://forum.strawberrymusicplayer.org/). 

**Describe the bug**
Crashes when an album is removed from playlist and another song is double clicked to be played, while "shuffle" is set to "shuffle albums".
Does NOT happen when next track is pressed

**To Reproduce**
1. Have playlist open, with "shuffle" set to "shuffle albums".
2. Remove all songs from an album from playlist.
3. Double click on any song in playlist OR add songs to playlist.

**Expected behavior**
No crash

**System Information:**
fedora 40
Strawberry Version 1.1.1

**Comment by jonaski** [comment]
```
#0  0x00007ffff469a25c in __pthread_kill_implementation () at /lib64/libc.so.6
#1  0x00007ffff46414b6 in raise () at /lib64/libc.so.6
#2  0x00007ffff462891a in abort () at /lib64/libc.so.6
#3  0x00000000004b40c8 in logging::MessageHandler (type=QtFatalMsg, message_log_context=..., message=...) at /home/jonas/Projects/strawberry/strawberry/src/core/logging.cpp:181
#4  0x00007ffff4eeb8f8 in qt_message_print (msgType=msgType@entry=QtFatalMsg, context=..., message=...) at /home/jonas/Projects/Qt/qtbase/qtbase/src/corelib/global/qlogging.cpp:2082
#5  0x00007ffff4eebb9a in qt_message(QtMsgType, const QMessageLogContext &, const char *, typedef __va_list_tag __va_list_tag *)
    (msgType=msgType@entry=QtFatalMsg, context=..., msg=msg@entry=0x7ffff52175f0 "ASSERT failure in %s: \"%s\", file %s, line %d", ap=ap@entry=0x7fffffff7270) at /home/jonas/Projects/Qt/qtbase/qtbase/src/corelib/global/qlogging.cpp:379
#6  0x00007ffff4ef0a73 in QMessageLogger::fatal (this=this@entry=0x7fffffff7498, msg=msg@entry=0x7ffff52175f0 "ASSERT failure in %s: \"%s\", file %s, line %d") at /home/jonas/Projects/Qt/qtbase/qtbase/src/corelib/global/qlogging.cpp:884
#7  0x00007ffff4ecfa18 in qt_assert_x (where=<optimized out>, what=<optimized out>, file=<optimized out>, line=<optimized out>) at /home/jonas/Projects/Qt/qtbase/qtbase/src/corelib/global/qassert.cpp:114
#8  0x00000000005adcda in QList<std::shared_ptr<PlaylistItem> >::operator[] (this=0x2d54270, i=-1) at /usr/local/qt6/include/QtCore/qlist.h:455
#9  0x0000000000781136 in Playlist::ReshuffleIndices (this=0x2d541b0) at /home/jonas/Projects/strawberry/strawberry/src/playlist/playlist.cpp:2014
#10 0x0000000000562006 in Player::PlayAt (this=0x184e720, index=15, pause=false, offset_nanosec=0, change=..., autoscroll=Playlist::AutoScroll::Never, reshuffle=true, force_inform=true) at /home/jonas/Projects/strawberry/strawberry/src/core/player.cpp:812
#11 0x00000000004d4a87 in MainWindow::PlaylistDoubleClick (this=0x7fffffffc6c0, idx=...) at /home/jonas/Projects/strawberry/strawberry/src/core/mainwindow.cpp:1593
#12 0x0000000000520ced in QtPrivate::FunctorCall<std::integer_sequence<unsigned long, 0ul>, QtPrivate::List<QModelIndex const&>, void, void (MainWindow::*)(QModelIndex const&)>::call(void (MainWindow::*)(QModelIndex const&), MainWindow*, void**)::{lambda()#1}::operator()() const (__closure=0x7fffffffb390) at /usr/local/qt6/include/QtCore/qobjectdefs_impl.h:127
#13 0x0000000000528ad8 in QtPrivate::FunctorCallBase::call_internal<void, QtPrivate::FunctorCall<std::integer_sequence<unsigned long, 0ul>, QtPrivate::List<QModelIndex const&>, void, void (MainWindow::*)(QModelIndex const&)>::call(void (MainWindow::*)(QModelIndex const&), MainWindow*, void**)::{lambda()#1}>(void**, QtPrivate::FunctorCall<std::integer_sequence<unsigned long, 0ul>, QtPrivate::List<QModelIndex const&>, void, void (MainWindow::*)(QModelIndex const&)>::call(void (MainWindow::*)(QModelIndex const&), MainWindow*, void**)::{lambda()#1}&&) (args=0x7fffffffb550, fn=...) at /usr/local/qt6/include/QtCore/qobjectdefs_impl.h:65
#14 0x0000000000520d50 in QtPrivate::FunctorCall<std::integer_sequence<unsigned long, 0ul>, QtPrivate::List<QModelIndex const&>, void, void (MainWindow::*)(QModelIndex const&)>::call
    (f=(void (MainWindow::*)(MainWindow * const, const QModelIndex &)) 0x4d4822 <MainWindow::PlaylistDoubleClick(QModelIndex const&)>, o=0x7fffffffc6c0, arg=0x7fffffffb550) at /usr/local/qt6/include/QtCore/qobjectdefs_impl.h:126
#15 0x0000000000517fd6 in QtPrivate::FunctionPointer<void (MainWindow::*)(QModelIndex const&)>::call<QtPrivate::List<QModelIndex const&>, void>
    (f=(void (MainWindow::*)(MainWindow * const, const QModelIndex &)) 0x4d4822 <MainWindow::PlaylistDoubleClick(QModelIndex const&)>, o=0x7fffffffc6c0, arg=0x7fffffffb550) at /usr/local/qt6/include/QtCore/qobjectdefs_impl.h:174
#16 0x000000000050f201 in QtPrivate::QCallableObject<void (MainWindow::*)(QModelIndex const&), QtPrivate::List<QModelIndex const&>, void>::impl (which=1, this_=0x25274c0, r=0x7fffffffc6c0, a=0x7fffffffb550, ret=0x0)
    at /usr/local/qt6/include/QtCore/qobjectdefs_impl.h:545
#17 0x00007ffff4fb8079 in QtPrivate::QSlotObjectBase::call (this=0x25274c0, r=0x7fffffffc6c0, a=0x7fffffffb550) at /home/jonas/Projects/Qt/qtbase/qtbase/src/corelib/kernel/qobjectdefs_impl.h:461
#18 doActivate<false> (sender=sender@entry=0x2353d00, signal_index=<optimized out>, argv=<optimized out>, argv@entry=0x7fffffffb550) at /home/jonas/Projects/Qt/qtbase/qtbase/src/corelib/kernel/qobject.cpp:4127
#19 0x00007ffff4fad6ab in QMetaObject::activate (sender=sender@entry=0x2353d00, m=m@entry=0x7ffff77cb3a0 <QAbstractItemView::staticMetaObject>, local_signal_index=local_signal_index@entry=2, argv=argv@entry=0x7fffffffb550)
    at /home/jonas/Projects/Qt/qtbase/qtbase/src/corelib/kernel/qobject.cpp:4187
#20 0x00007ffff7461112 in QAbstractItemView::doubleClicked (this=this@entry=0x2353d00, _t1=...) at /home/jonas/Projects/Qt/qtbase/build/src/widgets/Widgets_autogen/include/moc_qabstractitemview.cpp:907
#21 0x00007ffff74e4110 in QTreeView::mouseDoubleClickEvent (this=0x2353d00, event=0x7fffffffbd70) at /home/jonas/Projects/Qt/qtbase/qtbase/src/widgets/itemviews/qtreeview.cpp:2014
#22 0x00007ffff71f70db in QWidget::event (this=this@entry=0x2353d00, event=event@entry=0x7fffffffbd70) at /home/jonas/Projects/Qt/qtbase/qtbase/src/widgets/kernel/qwidget.cpp:8971
#23 0x00007ffff728fb34 in QFrame::event (this=this@entry=0x2353d00, e=e@entry=0x7fffffffbd70) at /home/jonas/Projects/Qt/qtbase/qtbase/src/widgets/widgets/qframe.cpp:521
#24 0x00007ffff728d2a8 in QAbstractScrollArea::viewportEvent (this=this@entry=0x2353d00, e=e@entry=0x7fffffffbd70) at /home/jonas/Projects/Qt/qtbase/qtbase/src/widgets/widgets/qabstractscrollarea.cpp:1064
#25 0x00007ffff746e57b in QAbstractItemView::viewportEvent (this=this@entry=0x2353d00, event=event@entry=0x7fffffffbd70) at /home/jonas/Projects/Qt/qtbase/qtbase/src/widgets/itemviews/qabstractitemview.cpp:1781
#26 0x00007ffff74e6985 in QTreeView::viewportEvent (this=0x2353d00, event=0x7fffffffbd70) at /home/jonas/Projects/Qt/qtbase/qtbase/src/widgets/itemviews/qtreeview.cpp:1313
#27 0x00007ffff728da2d in QAbstractScrollAreaPrivate::viewportEvent (this=<optimized out>, event=<optimized out>) at /home/jonas/Projects/Qt/qtbase/qtbase/src/widgets/widgets/qabstractscrollarea_p.h:74
#28 QAbstractScrollAreaFilter::eventFilter (this=<optimized out>, o=<optimized out>, e=<optimized out>) at /home/jonas/Projects/Qt/qtbase/qtbase/src/widgets/widgets/qabstractscrollarea_p.h:85
#29 0x00007ffff4f640a4 in QCoreApplicationPrivate::sendThroughObjectEventFilters (receiver=receiver@entry=0x2357340, event=event@entry=0x7fffffffbd70) at /home/jonas/Projects/Qt/qtbase/qtbase/src/corelib/kernel/qcoreapplication.cpp:1263
#30 0x00007ffff719abc1 in QApplicationPrivate::notify_helper (this=this@entry=0x16cd3f0, receiver=receiver@entry=0x2357340, e=0x7fffffffbd70) at /home/jonas/Projects/Qt/qtbase/qtbase/src/widgets/kernel/qapplication.cpp:3288
#31 0x00007ffff71a149d in QApplication::notify (this=<optimized out>, receiver=0x2357340, e=0x7fffffffbd70) at /home/jonas/Projects/Qt/qtbase/qtbase/src/widgets/kernel/qapplication.cpp:2772
#32 0x00007ffff4f6447e in QCoreApplication::notifyInternal2 (receiver=receiver@entry=0x2357340, event=event@entry=0x7fffffffbd70) at /home/jonas/Projects/Qt/qtbase/qtbase/src/corelib/kernel/qcoreapplication.cpp:1124
#33 0x00007ffff4f6457d in QCoreApplication::sendSpontaneousEvent (receiver=receiver@entry=0x2357340, event=event@entry=0x7fffffffbd70) at /home/jonas/Projects/Qt/qtbase/qtbase/src/corelib/kernel/qcoreapplication.cpp:1582
#34 0x00007ffff71a067c in QApplicationPrivate::sendMouseEvent
    (receiver=receiver@entry=0x2357340, event=event@entry=0x7fffffffbd70, alienWidget=alienWidget@entry=0x2357340, nativeWidget=0x7fffffffc6c0, buttonDown=buttonDown@entry=0x7ffff77e8b70 <qt_button_down>, lastMouseReceiver=..., spontaneous=true, onlyDispatchEnterLeave=false) at /home/jonas/Projects/Qt/qtbase/qtbase/src/widgets/kernel/qapplication.cpp:2353
#35 0x00007ffff720d531 in QWidgetWindow::handleMouseEvent (this=this@entry=0x2d68990, event=event@entry=0x7fffffffc1c0) at /home/jonas/Projects/Qt/qtbase/qtbase/src/widgets/kernel/qwidgetwindow.cpp:633
#36 0x00007ffff720f1e3 in QWidgetWindow::event (this=0x2d68990, event=0x7fffffffc1c0) at /home/jonas/Projects/Qt/qtbase/qtbase/src/widgets/kernel/qwidgetwindow.cpp:299
#37 0x00007ffff719abd1 in QApplicationPrivate::notify_helper (this=this@entry=0x16cd3f0, receiver=receiver@entry=0x2d68990, e=e@entry=0x7fffffffc1c0) at /home/jonas/Projects/Qt/qtbase/qtbase/src/widgets/kernel/qapplication.cpp:3294
#38 0x00007ffff71a2b70 in QApplication::notify (this=0x7fffffffcd00, receiver=0x2d68990, e=0x7fffffffc1c0) at /home/jonas/Projects/Qt/qtbase/qtbase/src/widgets/kernel/qapplication.cpp:3245
#39 0x00007ffff4f6447e in QCoreApplication::notifyInternal2 (receiver=receiver@entry=0x2d68990, event=event@entry=0x7fffffffc1c0) at /home/jonas/Projects/Qt/qtbase/qtbase/src/corelib/kernel/qcoreapplication.cpp:1124
#40 0x00007ffff4f6457d in QCoreApplication::sendSpontaneousEvent (receiver=receiver@entry=0x2d68990, event=event@entry=0x7fffffffc1c0) at /home/jonas/Projects/Qt/qtbase/qtbase/src/corelib/kernel/qcoreapplication.cpp:1582
#41 0x00007ffff67cc763 in QGuiApplicationPrivate::processMouseEvent (e=e@entry=0x2e5f320) at /home/jonas/Projects/Qt/qtbase/qtbase/src/gui/kernel/qguiapplication.cpp:2505
#42 0x00007ffff67cdead in QGuiApplicationPrivate::processWindowSystemEvent (e=e@entry=0x2e5f320) at /home/jonas/Projects/Qt/qtbase/qtbase/src/gui/kernel/qguiapplication.cpp:2192
#43 0x00007ffff68301b8 in QWindowSystemInterface::sendWindowSystemEvents (flags=flags@entry=...) at /home/jonas/Projects/Qt/qtbase/qtbase/src/gui/kernel/qwindowsysteminterface.cpp:1113
#44 0x00007ffff04f056e in xcbSourceDispatch (source=<optimized out>) at /home/jonas/Projects/Qt/qtbase/qtbase/src/plugins/platforms/xcb/qxcbeventdispatcher.cpp:57
#45 0x00007ffff54c8eb8 in ??? () at /lib64/libglib-2.0.so.0
#46 0x00007ffff54caca8 in ??? () at /lib64/libglib-2.0.so.0
#47 0x00007ffff54cb4bc in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#48 0x00007ffff51f0c51 in QEventDispatcherGlib::processEvents (this=0x176e230, flags=...) at /home/jonas/Projects/Qt/qtbase/qtbase/src/corelib/kernel/qeventdispatcher_glib.cpp:399
#49 0x00007ffff04f09c6 in QXcbGlibEventDispatcher::processEvents (this=<optimized out>, flags=...) at /home/jonas/Projects/Qt/qtbase/qtbase/src/plugins/platforms/xcb/qxcbeventdispatcher.cpp:96
#50 0x00007ffff4f6e39b in QEventLoop::processEvents (this=this@entry=0x7fffffffc590, flags=..., flags@entry=...) at /home/jonas/Projects/Qt/qtbase/qtbase/src/corelib/kernel/qeventloop.cpp:103
#51 0x00007ffff4f6ec4e in QEventLoop::exec (this=this@entry=0x7fffffffc590, flags=flags@entry=...) at /home/jonas/Projects/Qt/qtbase/qtbase/src/corelib/global/qflags.h:77
#52 0x00007ffff4f676bb in QCoreApplication::exec () at /home/jonas/Projects/Qt/qtbase/qtbase/src/corelib/global/qflags.h:77
#53 0x00000000004af6c1 in main (argc=1, argv=0x7fffffffd608) at /home/jonas/Projects/strawberry/strawberry/src/main.cpp:331

```
