### ISSUE TITLE
(macOS) macdeploy script fails (python)

### ISSUE THREAD

**Issue by jonaski** [strawberrymusicplayer/strawberry#493]
See: https://travis-ci.org/github/strawberrymusicplayer/strawberry/builds/713044176

```
Scanning dependencies of target dmg
Traceback (most recent call last):
  File "/Users/travis/build/strawberrymusicplayer/strawberry/dist/macos/macdeploy.py", line 490, in <module>
    main()
  File "/Users/travis/build/strawberrymusicplayer/strawberry/dist/macos/macdeploy.py", line 467, in main
    FixPlugin(FindGstreamerPlugin(plugin), 'gstreamer')
  File "/Users/travis/build/strawberrymusicplayer/strawberry/dist/macos/macdeploy.py", line 279, in FixPlugin
    FixAllLibraries(broken_libs)
  File "/Users/travis/build/strawberrymusicplayer/strawberry/dist/macos/macdeploy.py", line 236, in FixAllLibraries
    FixLibrary(lib)
  File "/Users/travis/build/strawberrymusicplayer/strawberry/dist/macos/macdeploy.py", line 267, in FixLibrary
    FixAllLibraries(broken_libs)
  File "/Users/travis/build/strawberrymusicplayer/strawberry/dist/macos/macdeploy.py", line 236, in FixAllLibraries
    FixLibrary(lib)
  File "/Users/travis/build/strawberrymusicplayer/strawberry/dist/macos/macdeploy.py", line 267, in FixLibrary
    FixAllLibraries(broken_libs)
  File "/Users/travis/build/strawberrymusicplayer/strawberry/dist/macos/macdeploy.py", line 236, in FixAllLibraries
    FixLibrary(lib)
  File "/Users/travis/build/strawberrymusicplayer/strawberry/dist/macos/macdeploy.py", line 266, in FixLibrary
    broken_libs = GetBrokenLibraries(abs_path)
  File "/Users/travis/build/strawberrymusicplayer/strawberry/dist/macos/macdeploy.py", line 195, in GetBrokenLibraries
    relative_path = os.path.join(*line.split('/')[3:])
TypeError: join() takes at least 1 argument (0 given)
make[3]: *** [CMakeFiles/dmg] Error 1
make[2]: *** [CMakeFiles/dmg.dir/all] Error 2
make[1]: *** [CMakeFiles/dmg.dir/rule] Error 2
make: *** [dmg] Error 2
```

**Comment by jonaski** [comment]
@NucleaPeon can you look at this? It works fine in my own macOS VM, but fails in travis-Ci. I can create a macos branch that you can try a fix in.
